const LOGIN: string = 'AUTH/LOGIN';
const LOGOUT: string = 'AUTH/LOGOUT';
const TOOGLE_IS_FETCHING: string = 'AUTH/TOOGLE_IS_FETCHING';
const FETCH_AUTH_FAILED: string = 'AUTH/FAILED';

export { LOGIN, LOGOUT, TOOGLE_IS_FETCHING, FETCH_AUTH_FAILED };
