const FETCH_DATA: string = 'MAIN/FETCH_DATA';
const FETCH_DATA_SUCCESS: string = 'MAIN/FETCH_DATA_SUCCESS';
const FETCH_DATA_ERROR: string = 'MAIN/FETCH_DATA_ERROR';
const EDIT_DATA: string = 'MAIN/EDIT_DATA';
const DELETE_DATA: string = 'MAIN/DELETE_DATA';

export {
  FETCH_DATA,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_ERROR,
  EDIT_DATA,
  DELETE_DATA,
};
