export enum ContactsActionTypes {
  FETCH_DATA = 'MAIN/FETCH_DATA',
  FETCH_DATA_SUCCESS = 'MAIN/FETCH_DATA_SUCCESS ',
  FETCH_DATA_ERROR = 'MAIN/FETCH_DATA_ERROR',
  EDIT_DATA = 'MAIN/EDIT_DATA',
  DELETE_DATA = 'MAIN/DELETE_DATA',
}
